apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: bns-mysql-svc         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: bns-mysql
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=social-login-app,tier=mysql`
    app: bns-mysql
---
apiVersion: apps/v1
kind: Deployment                    # Type of the kubernetes resource
metadata:
  name: bns-mysql-deployment           # Name of the deployment
  labels:                           # Labels applied to this deployment
    app: bns-mysql
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: bns-mysql
  strategy:
    type: Recreate
  template:                         # Template for the Pods in this deployment
    metadata:
      labels:                       # Labels to be applied to the Pods in this deployment
        app: bns-mysql
    spec:                           # The spec for the containers that will be run inside the Pods in this deployment
      containers:
      - image: docker.io/mysql            # The container image
        name: bns-mysql-container
        env:                        # Environment variables passed to the container
        - name: MYSQL_ROOT_PASSWORD
          value: "Sonamtenzin@1993"                # Read environment variables from kubernetes secrets
        - name: MYSQL_DATABASE
          value: "bns_enlistment"
        - name: MYSQL_USER
          value: "Sonamtenzin@1993"
        - name: MYSQL_PASSWORD
          value: "Sonamtenzin@1993"
        ports:
        - containerPort: 3306        # The port that the container exposes
          name: mysql

