apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:                    
  name: bns-api-svc    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: bns-api
spec:                        
  type: LoadBalancer              # The service will be exposed by opening a Port on each node and proxying it. 
  selector:
    app: bns-api   # The service exposes Pods with label `app=social-login-app-server`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 8080
    targetPort: 8080
